# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='course',
            field=models.ManyToManyField(related_name='users_of', to='courses.Course'),
        ),
    ]
